### ISSUE TITLE
support option to ensure webs responding to requests before load balancer updated

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dashboard-issues#37]
Currently deploy hooks can be used, but they don't run during a component scale. So either deploy hooks should also be run during a component scale or we need a boxfile directive. @sanderson suggested.

```
web.site:
  start: web-start-command
  preflight:
    - curl localhost:8080 ...
```
